IF EXISTS (SELECT name FROM master.sys.databases WHERE name = N'WebChat')
   print 'db exists'
ELSE
	CREATE DATABASE WEBCHAT
	print 'db created successfully'
GO

USE WEBCHAT
GO

CREATE TABLE [USER] (
	[UserName] CHAR(25) PRIMARY KEY,
	[Password] CHAR(25) NOT NULL,
	[Email] CHAR(50) NOT NULL UNIQUE,
	[FirstName] CHAR(100) NOT NULL,
	[SecondName] CHAR(100) NOT NULL,
	[BirthDate] DATE NOT NULL,
	[StatusID] TINYINT NOT NULL,
	[DateCreated] DATETIME2 NOT NULL DEFAULT GETDATE(),
);
GO

CREATE TABLE [CHATLIST] (
	[ID] BIGINT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50) NOT NULL,
	[Description] VARCHAR(255) NOT NULL,
	[Active] BIT NOT NULL,
	[DateCreated] DATETIME2 NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE [ROOM] (
	[UserName] CHAR(25) NOT NULL,
	[ChatListID] BIGINT NOT NULL,
	[DateCreated] DATETIME2 NOT NULL DEFAULT GETDATE(),
	PRIMARY KEY (UserName, ChatListID)
);
GO

CREATE TABLE [MESSAGE] (
	[ID] BIGINT PRIMARY KEY IDENTITY(1,1),
	[MESSAGE] VARCHAR(8000) NOT NULL,
	[StatusMessageID] TINYINT NOT NULL,
	[UserNameRoom] CHAR(25) NOT NULL,
	[ChatListIDRoom] BIGINT NOT NULL,
	[DateCreated] DATETIME2 NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE [STATUSUSER] (
	[ID] TINYINT PRIMARY KEY IDENTITY(1,1),
	[Name] CHAR(50) NOT NULL,
	[Description] VARCHAR(255) NOT NULL,
	[Active] BIT NOT NULL,
	[DateCreated] DATETIME2 NOT NULL
);
GO

ALTER TABLE [ROOM] ADD CONSTRAINT FK_UserName FOREIGN KEY([UserName]) REFERENCES [USER]([UserName]) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [ROOM] ADD CONSTRAINT FK_ChatListID FOREIGN KEY([ChatListID]) REFERENCES [CHATLIST]([ID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [MESSAGE] ADD CONSTRAINT FK_UserNameRoom FOREIGN KEY([UserNameRoom], [ChatListIDRoom]) REFERENCES [ROOM]([UserName],[ChatListID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE [USER] ADD CONSTRAINT FK_StatusID FOREIGN KEY([StatusID]) REFERENCES [STATUSUSER]([ID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO


INSERT INTO STATUSUSER (Name, Description, Active, DateCreated)
VALUES 
('Activo', 'El usuario se encuentra activo y puede hacer uso de la aplicación', 1, GETDATE()), 
('Inactivo', 'El usuario se encuentra inactivo y no puede hacer uso de la aplicación', 1, GETDATE());
GO